"use client"

import { useState } from "react"
import { ChevronDown } from "lucide-react"

const faqs = [
  {
    id: 1,
    question: "What is BrandByte?",
    answer:
      "BrandByte is an AI-powered platform that helps you generate high-converting ad creatives (compelling text and stunning visuals) quickly and easily for your marketing campaigns.",
  },
  {
    id: 2,
    question: "How does the AI generate ad creatives?",
    answer:
      "Our AI analyzes your product information, target audience, and campaign goals. It then uses advanced natural language processing and computer vision models to suggest effective copy, design elements, and layouts optimized for ad performance.",
  },
  {
    id: 3,
    question: "What types of ads can I create with BrandByte?",
    answer:
      "BrandByte supports a wide range of ad formats suitable for major platforms like Facebook, Instagram, Google Ads, LinkedIn, and more. This includes image ads, video ad concepts (storyboarding/scripts), carousel ads, and compelling text ads.",
  },
  {
    id: 4,
    question: "Do I need any design or copywriting skills to use BrandByte?",
    answer:
      "Not at all! BrandByte is designed for everyone, from solo entrepreneurs to large marketing teams. Our intuitive interface and AI assistance handle the heavy lifting for both creative generation and technical optimization.",
  },
  {
    id: 5,
    question: "Can I customize the ad creatives generated by the AI?",
    answer:
      "Yes, absolutely. The AI provides strong, data-driven starting points, but you have full control to edit, tweak, and customize every element of your ad creatives to perfectly match your brand voice and campaign requirements.",
  },
  {
    id: 6,
    question: "Is there a free trial or demo available?",
    answer:
      "Yes, BrandByte offers a free trial period so you can explore all the features and see how it can revolutionize your ad creation process. Sign up today to get started!", // TODO: Update if a demo or freemium plan is offered instead.
  },
]

export default function Faq() {
  const [openItem, setOpenItem] = useState<number | null>(null)

  const toggleItem = (id: number) => {
    setOpenItem(openItem === id ? null : id)
  }

  return (
    <section id="faq" className="my-20">
      <div className="card p-8 md:p-10 shadow-lg">
        <h2 className="text-black dark:text-white mb-6">
          Frequently Asked
          <span className="block text-[#7A7FEE] dark:text-[#7A7FEE]">Questions</span>
        </h2>
        <p className="mb-8 max-w-2xl text-gray-700 dark:text-gray-300">
          Have questions about BrandByte and how our AI can help you create amazing ad creatives? Find your answers here.
        </p>

        <div className="space-y-4">
          {faqs.map((faq) => (
            <div key={faq.id} className="border-b pb-4 border-gray-300 dark:border-gray-700">
              <button
                onClick={() => toggleItem(faq.id)}
                className="flex justify-between items-center w-full text-left py-2 font-medium text-black dark:text-white hover:text-[#7A7FEE] dark:hover:text-[#7A7FEE] transition-colors"
                aria-expanded={openItem === faq.id}
                aria-controls={`faq-answer-${faq.id}`}
              >
                <span className="font-medium">{faq.question}</span>
                <ChevronDown
                  className={`w-5 h-5 transition-transform ${openItem === faq.id ? "rotate-180 text-[#7A7FEE]" : ""}`}
                />
              </button>
              {openItem === faq.id && (
                <div id={`faq-answer-${faq.id}`} className="mt-2 text-gray-700 dark:text-gray-300">
                  {faq.answer}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
