"use client"

import Image from "next/image"
import { ArrowUpRight } from "lucide-react"

// Static ad creative data
const adCreatives = [
  {
    id: 1,
    image: "/ad1.jpg",
    title: "Foot Wear Campaign",
    description: "High-converting social media ad for foot retail"
  },
  {
    id: 2,
    image: "/ad2.jpg",
    title: "T-Shirt Campaign",
    description: "Eye-catching product showcase for t-shirt retail"
  },
  {
    id: 3,
    image: "/ad3.jpg",
    title: "Cake Shop Campaign",
    description: "Appetizing food photography for cake shop"
  },
  {
    id: 4,
    image: "/ad4.jpg",
    title: "Summer Sale Campaign",
    description: "special offer children"
  }
]

export default function Projects() {
  return (
    <section id="projects" className="my-20">
      <h2 className="text-black dark:text-white mb-6">
        See What BrandByte
        <span className="block text-[#7A7FEE] dark:text-[#7A7FEE]">Can Create</span>
      </h2>
      <p className="mb-12 max-w-2xl text-gray-700 dark:text-gray-300">
        Explore a gallery of high-impact ad creatives generated by BrandByte AI. See how we help businesses like yours
        boost engagement and conversions with stunning, data-driven designs.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {adCreatives.map((creative) => (
          <div
            key={creative.id}
            className="card overflow-hidden shadow-lg transform transition-transform duration-300 hover:scale-[1.02]"
          >
            <div className="flex items-center justify-center p-4 pt-6 bg-gray-100 dark:bg-gray-800 relative">
              <Image
                src={creative.image}
                alt={creative.title}
                width={600}
                height={400}
                className="w-full h-auto object-contain max-h-[220px]"
              />
            </div>
            <div className="p-4 md:p-6">
              <h3 className="text-xl font-semibold text-black dark:text-white">{creative.title}</h3>
              <p className="text-gray-700 dark:text-gray-300 text-sm mt-1 mb-4">{creative.description}</p>
            </div>
          </div>
        ))}
      </div>
    </section>
  )
}
